### ISSUE TITLE
responsivity ?

### ISSUE THREAD

**Issue by CYB3RL1F3** [Jam3/react-background-video-player#8]
Hello,

I constat a problem when I resize the page to a bigger definition : I can see the borders of the video and that doesn't cover anymore the whole background.

Any solution for this ?

**Comment by namniak** [comment]
First, you need to set `disableBackgroundCover` to `true`; also you have to pass the new `containerWidth/containerHeight` from the parent component. When your window/container size changes you need to pass the new values otherwise it's not going to resize. See the test https://github.com/Jam3/react-background-video-player/blob/master/test/test.js#L41. Basically, it's managed outside of the component.
